USE ROLE ACCOUNTADMIN;

DROP WAREHOUSE if exists ML_HOL_WH;
DROP STAGE if exists ML_HOL_DB.ML_HOL_SCHEMA.DIAMONDS_ASSETS;
DROP STAGE if exists ML_HOL_DB.ML_HOL_SCHEMA.ML_HOL_ASSETS;
DROP SCHEMA if exists ML_HOL_DB.ML_HOL_SCHEMA;
DROP DATABASE if exists ML_HOL_DB.ML_HOL_DB;
